name: Deploy OrderService and ProductMicroservice

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PRODUCTSERVICES_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PRODUCTSERVICES_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PRODUCTSERVICES_AZURE_SUBSCRIPTION_ID }}

      # -------------------- OrderService --------------------
      - name: Deploy OrderService
        uses: azure/container-apps-deploy-action@v2
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

          resourceGroup: ms
          containerAppEnvironment: test
          containerAppName: orderservice

          appSourcePath: OrderService
          dockerfilePath: DockerFile
          targetPort: 80

      # -------------------- ProductMicroservice --------------------
      - name: Deploy ProductMicroservice
        uses: azure/container-apps-deploy-action@v2
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

          resourceGroup: ms
          containerAppEnvironment: test
          containerAppName: productservice

          appSourcePath: ProductMicroservice
          dockerfilePath: DockerFile
          targetPort: 80
